# THIS FILE IS AUTOGENERATED, DO NOT EDIT!!!
#
# Cambalache Object wrappers
#
# Copyright (C) 2021  Juan Pablo Ugarte - All Rights Reserved
#
# Unauthorized copying of this file, via any medium is strictly prohibited.
#

import gi
from gi.repository import GObject


class CmbUI(GObject.GObject):
    ui_id = GObject.Property(type=int, flags = GObject.ParamFlags.READWRITE | GObject.ParamFlags.CONSTRUCT_ONLY)
    template_id = GObject.Property(type=int)
    name = GObject.Property(type=str)
    filename = GObject.Property(type=str)
    description = GObject.Property(type=str)
    copyright = GObject.Property(type=str)
    authors = GObject.Property(type=str)
    license_id = GObject.Property(type=str)
    translation_domain = GObject.Property(type=str)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)


class CmbProperty(GObject.GObject):
    ui_id = GObject.Property(type=int, flags = GObject.ParamFlags.READWRITE | GObject.ParamFlags.CONSTRUCT_ONLY)
    object_id = GObject.Property(type=int, flags = GObject.ParamFlags.READWRITE | GObject.ParamFlags.CONSTRUCT_ONLY)
    owner_id = GObject.Property(type=str, flags = GObject.ParamFlags.READWRITE | GObject.ParamFlags.CONSTRUCT_ONLY)
    property_id = GObject.Property(type=str, flags = GObject.ParamFlags.READWRITE | GObject.ParamFlags.CONSTRUCT_ONLY)
    value = GObject.Property(type=str)
    translatable = GObject.Property(type=bool, default = False)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)


class CmbSignal(GObject.GObject):
    ui_id = GObject.Property(type=int)
    object_id = GObject.Property(type=int)
    owner_id = GObject.Property(type=str)
    signal_id = GObject.Property(type=str)
    handler = GObject.Property(type=str)
    detail = GObject.Property(type=str)
    user_data = GObject.Property(type=int)
    swap = GObject.Property(type=bool, default = False)
    after = GObject.Property(type=bool, default = False)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)


class CmbObject(GObject.GObject):
    ui_id = GObject.Property(type=int, flags = GObject.ParamFlags.READWRITE | GObject.ParamFlags.CONSTRUCT_ONLY)
    object_id = GObject.Property(type=int, flags = GObject.ParamFlags.READWRITE | GObject.ParamFlags.CONSTRUCT_ONLY)
    type_id = GObject.Property(type=str)
    name = GObject.Property(type=str)
    parent_id = GObject.Property(type=int)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
